# Generated by Django 5.1.5 on 2025-03-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0023_petprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petprofile',
            name='user',
        ),
    ]
